### ISSUE TITLE
Getting decrypted data using CryptLib 

### ISSUE THREAD

**Issue by manishmundra3** [Pakhee/Cross-platform-AES-encryption#15] opened 2015-06-16 10:25 UTC
// My testing string is "This is test Encryption String Two"

NSString *str=[[NSBundle mainBundle] pathForResource:@"data" ofType:@"rtf"];
NSData *data = [NSData dataWithContentsOfFile:str];

NSString *iv = @"VFSGlobalApp";
NSString *key = [[CryptLib alloc]sha256:@"VFSGlobalApp" length:31];//getHashSha256(@"VFSGlobalApp", 31); //32 bytes

NSData *dataencrypt = [[CryptLib alloc]encrypt:data key:key iv:iv];
NSData *base64 = [dataencrypt base64EncodedDataWithOptions:0];
NSString *sBase64 = [[NSString alloc] initWithData:base64 encoding:NSUTF8StringEncoding];
NSLog(@"Base64 String: %@",sBase64);

NSData *datadecrypt = [[CryptLib alloc]decrypt:dataencrypt key:key iv:iv];
NSString *sDecrypt = [[NSString alloc] initWithData:datadecrypt encoding:NSUTF8StringEncoding];
NSLog(@"Decrypted Data: %@",sDecrypt);

***********************
Decrypted Data: {\rtf1\ansi\ansicpg1252\cocoartf1347\cocoasubrtf570
{\fonttbl\f0\fmodern\fcharset0 CourierNewPSMT;\f1\froman\fcharset0 TimesNewRomanPSMT;}
{\colortbl;\red255\green255\blue255;\red163\green21\blue21;}
\margl1440\margr1440\vieww9000\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs20 \cf2 This is test Encryption String Two
\f1\fs24 \cf0 \
}
*******************
Please help me out.

**Comment by navneet83** [comment] 2015-06-16 18:10
What is the expected Decrypted data ? This looks like duplicate of this issue - https://github.com/Pakhee/Cross-platform-AES-encryption/issues/10#issuecomment-91379847

Make sure your IV is 16 characters and consider randomizing your IV.

**Comment by manishmundra3** [comment] 2015-06-17 04:23
Hello Navneet,
My encrypted string is :
*97Dfy+pLJFA+RqYR8nX8YFr6JuVC5UUOQceV93kN4aUU+qUvjMa+2Z1iifcrG/U6*

Actual string is :

This is test Encryption String One


string iv = "VFSGlobalApp";

string key = CryptLib.getHashSha256("VFSGlobalApp", 31); //32 bytes = 256
bits


Then i decrypt this encrypted text then i get nothing.




Thanks & Regards,
*Manish Mundra*
Cell No. +91-898-957-7549 (MP) | +91-940-813-1268 (GJ)
Skype: *manishmundra3*
Facebook:* https://www.facebook.com/mainshalbum
<http://www.facebook.com/mainshalbum>*

**Comment by navneet83** [comment] 2015-06-17 04:26
Did you read my previous comment and implement changes accordingly ?

**Comment by manishmundra3** [comment] 2015-06-17 05:31
Yes, i did but response is not according my encrypted string.

    NSString *iv = @"GlobalApp";

    NSString *key = [[CryptLib alloc]sha256:@"GlobalApp"
length:32];//getHashSha256(@"GlobalApp", 31); //32 bytes

    NSString * secret = @"This is test Encryption String Two";

   * Output : *

*r+jolqNoBBq/XCV9rrXzQwmFt8jCD/AHYdzIG/ECVUAVFsAIaYOQy+xzYrq8/Ayx*


    NSData * encryptedData = [[CryptLib alloc] encrypt:[secret
dataUsingEncoding:NSUTF8StringEncoding] key:key iv:iv];

    NSString *encryptedText = [encryptedData
 base64EncodingWithLineLength:0];

    NSData * decryptedData = [[CryptLib alloc] decrypt:[encryptedText
dataUsingEncoding:NSUTF8StringEncoding]  key:key iv:iv];

    NSString * decryptedText = [decryptedData
 base64EncodingWithLineLength:0];

   *Output : *

*Mk8OOh3yQ3KyddqzQ/xjReakOoUMcXBGXmZT0ZzUNrGNgRF/rwFkGZBup3j0k5LT5Cw3x+9201F89ri3l610qg==*


Thanks & Regards,
*Manish Mundra*
Cell No. +91-898-957-7549 (MP) | +91-940-813-1268 (GJ)
Skype: *manishmundra3*
Facebook:* https://www.facebook.com/mainshalbum
<http://www.facebook.com/mainshalbum>*

**Comment by navneet83** [comment] 2015-06-17 05:55
What is your IV ? In your code you have used -     NSString *iv = @"GlobalApp";  This has just 9 characters while I had mentioned that you'll need at least 16 characters.

**Closed** 2015-06-19 08:28 UTC
Labels: question

**Comment by manishmundra3** [comment] 2015-07-21 11:04
Referral Bonus                                    Hey there,       
Your friend has invited you to experience PayUMoney.     PayUMoney allows
you to pay using your existing Credit/Debit Card and NetBanking. The best
part of PayUMoney experience is that you get upto 10% Discount everytime
you pay using PayUMoney.           Accept Invite
<https://www.payumoney.com/?refcode=8337e73d45d6ce46caad4d8956d2bfa9&source=gmail>
       (You are referred by your friend with mundramanish3@gmail.com)      
 To see list of 25000+ merchants which accept PayUMoney,  Click here
<https://www.payumoney.com/cashback.html?refcode=8337e73d45d6ce46caad4d8956d2bfa9&source=gmail>
    *You need to do your first transaction of minimum Rs 250/-
*Not applicable for recharge transactions like Mobile, DTH and Data Cards
recharge etc.        Happy buying and more,    Team PayUMoney              
  For any issues at all, please reach us at care@payumoney.com
<mailto:care@payumoney.com> <https://www.facebook.com/payumoney>
<https://twitter.com/payumoney>
<http://www.linkedin.com/company/payu-india-internet-pvt-ltd-?trk=cp_followed_name_payu-india-internet-pvt-ltd>
